
spring:
  profiles:
    active: local
server:
  port: 8080

---
spring:
  profiles: local
  kafka:
    template:
      default-topic: station-events
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-listener-group
    producer:
      bootstrap-servers:
        -   localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:mysql://localhost:3306/stations
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: akash1234

  jpa:
    hibernate.ddl-auto: update
#  h2:
#    console:
#      enabled: true


---

#spring:
#  profiles: nonprod
#  kafka:
#    template:
#      default-topic: library-events
#    consumer:
#      bootstrap-servers: localhost:9092
#      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      group-id: library-events-listener-group
#      ssl:
#        trust-store-location: file:/Dilip/udemy/kafka-for-developers-using-spring-boot/ssl/client.truststore.jks
#        trust-store-password: password
#        key-store-location: file:/Dilip/udemy/kafka-for-developers-using-spring-boot/ssl/client.keystore.jks
#        key-store-password: password
#    producer:
#      bootstrap-servers:
#        -   localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    properties:
#      security:
#        protocol: SSL
#      ssl.endpoint.identification.algorithm:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#  jpa:
#    database: h2
#    database-platform: org.hibernate.dialect.H2Dialect
#    generate-ddl: true
#  h2:
#    console:
#      enabled: true
#
#---
#
#spring:
#  profiles: prod
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      group-id: library-events-listener-group


