spring:
  profiles:
    active: local
server:
  port: 8082

---
spring:
  profiles: local
  kafka:
    template:
      default-topic: station-events
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-listener-group
    producer:
      bootstrap-servers:
        -   localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:mysql://localhost:3306/stations
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: akash1234

  jpa:
    hibernate.ddl-auto: update